### ISSUE TITLE
compile issues for gcc

### ISSUE THREAD

**Issue by NEWPLAN** [jcf94/multithread_case#1]
Hi, 
看到你的博客写的很棒，顺便跑了一下你的代码，发现有一些小问题，你的这个project中的makefile可能因为GCC版本的问题，编译会出现一些错误。

建议:
在 CFLAGS 后面加上-std=c++14
链接标识符加上-lpthread

祝好！

**Comment by jcf94** [comment]
多谢提醒，当时瞎写的时候直接在 windows 下面用 Mingw 编的，估计对应的 gcc 版本比较高，刚刚拿低版本的试了下确实有问题......
非常感谢~~
